# Generated by Django 3.2.8 on 2021-10-11 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=128)),
                ('telephone', models.CharField(blank=True, max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='practice.contract')),
            ],
        ),
    ]
